import { Product } from '../../app/core/models/product.model';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ethiopian Yirgacheffe',
    description: 'A light roasted coffee with bright acidity and complex floral and citrus notes. This single-origin coffee comes from the Yirgacheffe region in Ethiopia, known for producing some of the world\'s finest coffees.',
    price: 18.99,
    imageUrl: 'https://images.pexels.com/photos/2252513/pexels-photo-2252513.jpeg',
    category: 'single-origin',
    origin: 'Ethiopia',
    roastLevel: 'Light',
    flavourNotes: ['Floral', 'Citrus', 'Bergamot'],
    weight: 340,
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 124
  },
  {
    id: '2',
    name: 'Colombian Supremo',
    description: 'A medium roasted coffee with a smooth body and sweet caramel notes. This single-origin coffee comes from the high-altitude regions of Colombia, offering a classic and balanced flavor profile.',
    price: 16.99,
    imageUrl: 'https://images.pexels.com/photos/2478327/pexels-photo-2478327.jpeg',
    category: 'single-origin',
    origin: 'Colombia',
    roastLevel: 'Medium',
    flavourNotes: ['Caramel', 'Almond', 'Red Apple'],
    weight: 340,
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 89
  },
  {
    id: '3',
    name: 'Sumatra Mandheling',
    description: 'A dark roasted coffee with a full body and earthy, herbal notes. This single-origin coffee comes from the volcanic soils of Sumatra, Indonesia, known for its distinctive flavor profile and low acidity.',
    price: 17.99,
    imageUrl: 'https://images.pexels.com/photos/4820687/pexels-photo-4820687.jpeg',
    category: 'single-origin',
    origin: 'Indonesia',
    roastLevel: 'Dark',
    flavourNotes: ['Earthy', 'Herbal', 'Dark Chocolate'],
    weight: 340,
    inStock: true,
    featured: false,
    rating: 4.3,
    reviewCount: 67
  },
  {
    id: '4',
    name: 'Morning Blend',
    description: 'A balanced blend of Latin American coffees with a smooth body and notes of chocolate and nuts. Perfect for starting your day with a familiar and comforting cup.',
    price: 15.99,
    imageUrl: 'https://images.pexels.com/photos/2396220/pexels-photo-2396220.jpeg',
    category: 'blends',
    origin: 'Latin America',
    roastLevel: 'Medium',
    flavourNotes: ['Chocolate', 'Nuts', 'Caramel'],
    weight: 340,
    inStock: true,
    featured: true,
    rating: 4.6,
    reviewCount: 112
  },
  {
    id: '5',
    name: 'Espresso Roast',
    description: 'A dark roasted blend specifically crafted for espresso with a rich crema and notes of dark chocolate and caramel. This blend combines beans from different regions to create the perfect espresso shot.',
    price: 17.99,
    imageUrl: 'https://images.pexels.com/photos/374147/pexels-photo-374147.jpeg',
    category: 'espresso',
    origin: 'Multi-Region',
    roastLevel: 'Dark',
    flavourNotes: ['Dark Chocolate', 'Caramel', 'Brown Sugar'],
    weight: 340,
    inStock: true,
    featured: true,
    rating: 4.7,
    reviewCount: 95
  },
  {
    id: '6',
    name: 'Swiss Water Decaf',
    description: 'A medium roasted decaffeinated coffee processed using the Swiss Water method, which removes caffeine without chemicals. Enjoy the full flavor of coffee without the caffeine.',
    price: 18.99,
    imageUrl: 'https://images.pexels.com/photos/585750/pexels-photo-585750.jpeg',
    category: 'decaf',
    origin: 'Brazil',
    roastLevel: 'Medium',
    flavourNotes: ['Chocolate', 'Almond', 'Sweet'],
    weight: 340,
    inStock: true,
    featured: false,
    rating: 4.2,
    reviewCount: 42
  },
  {
    id: '7',
    name: 'Kenya AA',
    description: 'A light-medium roasted coffee with bright acidity and fruity, wine-like notes. This single-origin coffee comes from Kenya\'s high plateaus, known for producing beans with complex flavors.',
    price: 19.99,
    imageUrl: 'https://images.pexels.com/photos/4196907/pexels-photo-4196907.jpeg',
    category: 'single-origin',
    origin: 'Kenya',
    roastLevel: 'Medium-Light',
    flavourNotes: ['Blackcurrant', 'Wine', 'Citrus'],
    weight: 340,
    inStock: true,
    featured: false,
    rating: 4.9,
    reviewCount: 76
  },
  {
    id: '8',
    name: 'Guatemala Antigua',
    description: 'A medium roasted coffee with a well-balanced body and complex flavor profile including notes of cocoa, spice, and subtle fruitiness. This coffee comes from the Antigua region of Guatemala.',
    price: 17.99,
    imageUrl: 'https://images.pexels.com/photos/1170659/pexels-photo-1170659.jpeg',
    category: 'single-origin',
    origin: 'Guatemala',
    roastLevel: 'Medium',
    flavourNotes: ['Cocoa', 'Spice', 'Apple'],
    weight: 340,
    inStock: true,
    featured: false,
    rating: 4.4,
    reviewCount: 58
  }
];